### ISSUE TITLE
ImportError: libtaso_runtime.so

### ISSUE THREAD

**Issue by sandeepnmenon** [jiazhihao/TASO#105]
I installed the docker image on my cluster with a V100 GPU.
From the docker interactive
```bash
 nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```
But when I run `import taso` I get
```bash
>>> import taso
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/taso-0.1.0-py3.7-linux-x86_64.egg/taso/__init__.py", line 1, in <module>
    from .core import *
ImportError: libtaso_runtime.so: cannot open shared object file: No such file or directory
```

I used the `tasoml/cuda100` docker image.
What could be the issue?

**Comment by foxFakeL** [comment]
install nvidia-container-toolkit and add `--gpus all` args when you start the container
