### ISSUE TITLE
Runtime Error: ImportError: No module named core

### ISSUE THREAD

**Issue by XiaotaoChen** [jiazhihao/TASO#29]
I build `TASO` from source according the install doc.
```shell
mkdir build; cd build; cmake ..
sudo make install -j 4
cd ../python
python setup.py install
```
**the output info of  `cmake ..`  as below:**
```shell
-- The CXX compiler identification is GNU 5.4.0
-- The CUDA compiler identification is NVIDIA 9.0.176
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Found Protobuf: /root/3rdparty/protobuf-3.9.0/lib/libprotobuf.so;-lpthread (found version "3.9.0") 
-- PROTOBUF=/root/3rdparty/protobuf-3.9.0/lib/libprotobuf.so
-- Performing Test SUPPORT_CXX11
-- Performing Test SUPPORT_CXX11 - Success
-- Found Threads: TRUE  
-- Found CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda
-- Found CUDA_CUDA_LIBRARY=/usr/local/cuda/targets/x86_64-linux/lib/stubs/libcuda.so
-- Found CUDA_CUDART_LIBRARY=/usr/local/cuda/lib64/libcudart.so
-- Found CUDA_NVRTC_LIBRARY=/usr/local/cuda/lib64/libnvrtc.so
-- Found CUDA_CUDNN_LIBRARY=/usr/lib/x86_64-linux-gnu/libcudnn.so
-- Found CUDA_CUBLAS_LIBRARY=/usr/local/cuda/lib64/libcublas.so
-- CUDA_INCLUDE_DIR=/usr/local/cuda/include
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/tscpfs2/xiaotao.chen/Repositories/TASO/build
```
**the output info of `make install -j` as below:**
```shell
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/libtaso_runtime.so
-- Set runtime path of "/usr/local/lib/libtaso_runtime.so" to ""
-- Up-to-date: /usr/local/./include
-- Installing: /usr/local/./include/taso
-- Installing: /usr/local/./include/taso/ops.h
-- Installing: /usr/local/./include/taso/substitution.h
-- Installing: /usr/local/./include/taso/cuda_helper.h
```
**after run `python setup.py install`, to check taso is installed by `pip list|grep taso` **
```shell
taso                               0.1.0 
```
**Then i try to run the example with the script `python examples/resnext50.py`, and it shows:**
```shell
Traceback (most recent call last):
  File "examples/resnext50.py", line 1, in <module>
    import taso as ts
  File "/mnt/tscpfs2/xiaotao.chen/Repositories/TASO/python/taso/__init__.py", line 1, in <module>
    from .core import *
ImportError: No module named core
```
I don't know which step i missed. May your help, Thanks. @jiazhihao

**Comment by jiazhihao** [comment]
@XiaotaoChen I saw you have a new post. Have you fixed this issue?

**Comment by XiaotaoChen** [comment]
@jiazhihao Thanks, That should be some errors in my envs. I rebuild a docker with your `Dockerfile`, It's work normally.
