### ISSUE TITLE
Gpt2-10 model from onnx-models: Graph must be in single static assignment (SSA) form

### ISSUE THREAD

**Issue by sergei-mironov** [jiazhihao/TASO#67]
Here is the error I found after applying TASO (commit dce8c4d967f ) to the GPT-2 model of [onnx-models](https://github.com/onnx/models/).

```
Traceback (most recent call last):
  File "taso/examples/test_onnx.py", line 19, in <module>
    onnx.checker.check_model(onnx_model)
  File "/opt/conda/lib/python3.8/site-packages/onnx/checker.py", line 91, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Graph must be in single static assignment (SSA) form, however 'data' has been used as graph input names multiple times.
```

**Comment by peterlau123** [comment]
This may be due to ONNX version problem.
You can skip onnx.checker.check_model(onnx_model) and just export
exported model can be visualized by Netron also

**Comment by markuswt** [comment]
#97 should fix this
