### ISSUE TITLE
Unsupported ONNX operator: Squeeze

### ISSUE THREAD

**Issue by olivia111** [jiazhihao/TASO#7]
Traceback (most recent call last):
  File "examples/test_onnx.py", line 4, in <module>
    graph = taso.load_onnx("/home/taso/yolov3.onnx")
  File "/home/.local/lib/python3.7/site-packages/taso-0.1.0-py3.7-linux-x86_64.egg/taso/__init__.py", line 459, in load_onnx
    assert False, "Unsupported ONNX operator: {}".format(op.op_type)
AssertionError: Unsupported ONNX operator: Squeeze
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "examples/test_onnx.py", line 4, in <module>
    graph = taso.load_onnx("/home/taso/yolov3.onnx")
  File "/home/.local/lib/python3.7/site-packages/taso-0.1.0-py3.7-linux-x86_64.egg/taso/__init__.py", line 459, in load_onnx
    assert False, "Unsupported ONNX operator: {}".format(op.op_type)
AssertionError: Unsupported ONNX operator: Squeeze

**Comment by jiazhihao** [comment]
Support for Squeeze has been added.
