### ISSUE TITLE
Meets 'ImportErrot' when import taso

### ISSUE THREAD

**Issue by xuguanming** [jiazhihao/TASO#73]
Hello All

I build TASO on ubuntu16.04(no cuda) and meet error when 'import taso' in python3.
here is error info:

Python 3.5.2 (default, Oct  7 2020, 17:19:02) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import taso
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/taso-0.1.0-py3.5-linux-x86_64.egg/taso/__init__.py", line 1, in <module>
    from .core import *
ImportError:  sdk/TASO/build/libtaso_runtime.so: undefined symbol: _ZN4taso10Activation7forwardEb

THX

**Comment by Pegessi** [comment]
It seems that you have not build the libtaso_runtime.so
