### ISSUE TITLE
ImportError when  import taso 

### ISSUE THREAD

**Issue by MingliSun** [jiazhihao/TASO#85]
I build TASO on ubuntu18.04(on cuda) and meet error when 'import taso' in python3.
here is error info:

Python 3.8.6 (default, Oct  6 2020, 03:22:36) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import taso
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/taso-0.1.0-py3.8-linux-x86_64.egg/taso/__init__.py", line 1, in <module>
    from .core import *
ImportError: libtaso_runtime.so: cannot open shared object file: No such file or directory

And a Cmake Warning occured when cmake it and it seems it doesn't matter.

CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "taso_runtime".
This warning is for project developers.  Use -Wno-dev to suppress it.

Thanks

**Comment by Sagebati** [comment]
I had the same problem, did you find any solution (I'm using a conda environment)? I had the same cmake warning

**Comment by KevinZ-718** [comment]
you can try `cp /usr/local/lib/libtaso_runtime.so /home/yourname/anaconda3/lib/`

**Comment by DLYLL** [comment]
1. find libtaso_runtime.so, it maybe in /usr/local/lib
2. then, add this path to your LD_LIBRARY_PATH=/usr/local/lib
it works for me.
